### ISSUE TITLE
Crash'N'Burn crash issue

### ISSUE THREAD

**Issue by NicknineTheEagle** [nikita36078/J2ME-Loader#1012]
### Emulator version

1.7.9

### Game version

1.0.7

### Game resolution

176x220

### Device

Samsung Galaxy S23

### Android version

Android 13

### Description of the issue

Crash'N'Burn always crashes after finishing a race and entering player name for high scores table.

**Comment by NicknineTheEagle** [comment]
Exempt from log:
```
08-14 14:47:14.850  7419  7419 E AndroidRuntime: FATAL EXCEPTION: main
08-14 14:47:14.850  7419  7419 E AndroidRuntime: Process: ru.playsoftware.j2meloader:midlet, PID: 7419
08-14 14:47:14.850  7419  7419 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.removeViewAt(int)' on a null object reference
08-14 14:47:14.850  7419  7419 E AndroidRuntime: 	at javax.microedition.lcdui.Form.lambda$delete$3(Unknown Source:2)
08-14 14:47:14.850  7419  7419 E AndroidRuntime: 	at javax.microedition.lcdui.Form.e(Unknown Source:0)
08-14 14:47:14.850  7419  7419 E AndroidRuntime: 	at javax.microedition.lcdui.j.run(Unknown Source:4)
08-14 14:47:14.850  7419  7419 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
08-14 14:47:14.850  7419  7419 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-14 14:47:14.850  7419  7419 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
08-14 14:47:14.850  7419  7419 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
08-14 14:47:14.850  7419  7419 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8757)
08-14 14:47:14.850  7419  7419 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-14 14:47:14.850  7419  7419 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
08-14 14:47:14.850  7419  7419 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by StanleyKid-22** [comment]
Checked on 1.8.2.1807, Android 10, issue looks like fixed.
