### ISSUE TITLE
Diamond Rush 240x320 Error Installing

### ISSUE THREAD

**Issue by oatmeal01** [nikita36078/J2ME-Loader#125]
This happens when i try to install the game.
>![screenshot_2018-02-22-05-11-54](https://user-images.githubusercontent.com/36059629/36505645-2794de5c-178f-11e8-8cf9-567ede0ee1ac.png)

**Comment by nikita36078** [comment]
It is converting issue, I can't fix it, at least now.

**Comment by oatmeal01** [comment]
my device is Android 5.0 Lolipop version

**Comment by nikita36078** [comment]
I was wrong then :) It definitely works on 7.1, 8.0 and 8.1, so I thought it is a dalvik bug, but if it works on 5.0 then it is something different.

**Comment by oatmeal01** [comment]
ill try it on other os 5.0 device, my os 5.0 is x86 btw

**Comment by oatmeal01** [comment]
Same issue with android os 6.0.1

**Comment by jasper1412** [comment]
I get this error too on some bundled EA game, my device is lollipop-5.1

**Comment by nikita36078** [comment]
Yes, unfortunately there is a lot of games with this issue.

**Comment by jack1432** [comment]
I also have this same problem with Diamond Rush. I tested it on three devices with different versions of Android:
Android: 4.1.2 (works)
Android: 5.1.1 (did not work)
Android: 6.0.1 (did not work).
I only managed to play on Android 4.1.2

**Comment by oatmeal01** [comment]
tested on Android OS 4.4.2 Kitkat and it works

**Comment by AdityaMH** [comment]
if the problem is about dalvik cache, maybe it will work if phone is rooted? *just wondering*

**Comment by nikita36078** [comment]
I heard about some workarounds with editing build.prop, but I can't guarantee that it will work and won't break your phone.

**Comment by AdityaMH** [comment]
I think that not recommended even know about android system code.

**Comment by GauravM512** [comment]
Yeah it works on 7.1

**Comment by fieryjack55** [comment]
Works with android 7 on samsung tablet

**Comment by mrroniellelubay336** [comment]
Hey, When did you fix this issue about "Diamond Rush 240x320 Error when Opening"? Its 2020 but it can't be worked for my device version is Samsung J2 Prime (6.0.1)

**Comment by W1nKille3r** [comment]
Confirm it on clear 6.0 ROM. Device rooted. Clearing Dalvik-Cache doesn't work. Funny enough - those games worked fine before i wiped J2ME

```
====================Error==================
java.lang.RuntimeException: Init midlet failed
	at javax.microedition.shell.MidletThread.handleMessage(MidletThread.java:25)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:207)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance(Native Method)
	at javax.microedition.shell.MicroLoader.loadMIDlet(MicroLoader.java:15)
	at javax.microedition.shell.MidletThread.handleMessage(MidletThread.java:23)
	... 3 more
Caused by: java.lang.VerifyError: Rejecting class j because it failed compile-time verification (declaration of 'j' appears in /storage/emulated/0/J2ME-Loader/converted/Diamond Rush Konon.Mobi/converted.dex)
	at GloftDIRU.<init>(Unknown Source)
	... 6 more
```

**Comment by W1nKille3r** [comment]
Same happens with City Bloxx. Btw my memory is SD Card+Internal. Maybe this is connected?

```
=================Error==================
java.lang.RuntimeException: Init midlet failed
	at javax.microedition.shell.MidletThread.handleMessage(MidletThread.java:25)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:207)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance(Native Method)
	at javax.microedition.shell.MicroLoader.loadMIDlet(MicroLoader.java:15)
	at javax.microedition.shell.MidletThread.handleMessage(MidletThread.java:23)
	... 3 more
Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/ru.playsoftware.j2meloader-1/base.apk"],nativeLibraryDirectories=[/data/app/ru.playsoftware.j2meloader-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libjavam3g.so"
	at java.lang.Runtime.loadLibrary(Runtime.java:367)
	at java.lang.System.loadLibrary(System.java:1076)
	at javax.microedition.m3g.Platform.uiThreadAvailable(Platform.java:2)
	at javax.microedition.m3g.Interface.initNativePeer(Interface.java:2)
	at javax.microedition.m3g.Interface.<init>(Interface.java:5)
	at javax.microedition.m3g.Interface.getInstance(Interface.java:2)
	at javax.microedition.m3g.Graphics3D.<init>(Graphics3D.java:8)
	at javax.microedition.m3g.Graphics3D.getInstance(Graphics3D.java:2)
	at n.a(Unknown Source)
	at House.<init>(Unknown Source)
	... 6 more
```

**Comment by fireclouu** [comment]
> Same happens with City Bloxx. Btw my memory is SD Card+Internal. Maybe this is connected?
> 
> ```
> =================Error==================
> java.lang.RuntimeException: Init midlet failed
> 	at javax.microedition.shell.MidletThread.handleMessage(MidletThread.java:25)
> 	at android.os.Handler.dispatchMessage(Handler.java:107)
> 	at android.os.Looper.loop(Looper.java:207)
> 	at android.os.HandlerThread.run(HandlerThread.java:61)
> Caused by: java.lang.reflect.InvocationTargetException
> 	at java.lang.reflect.Constructor.newInstance(Native Method)
> 	at javax.microedition.shell.MicroLoader.loadMIDlet(MicroLoader.java:15)
> 	at javax.microedition.shell.MidletThread.handleMessage(MidletThread.java:23)
> 	... 3 more
> Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/ru.playsoftware.j2meloader-1/base.apk"],nativeLibraryDirectories=[/data/app/ru.playsoftware.j2meloader-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libjavam3g.so"
> 	at java.lang.Runtime.loadLibrary(Runtime.java:367)
> 	at java.lang.System.loadLibrary(System.java:1076)
> 	at javax.microedition.m3g.Platform.uiThreadAvailable(Platform.java:2)
> 	at javax.microedition.m3g.Interface.initNativePeer(Interface.java:2)
> 	at javax.microedition.m3g.Interface.<init>(Interface.java:5)
> 	at javax.microedition.m3g.Interface.getInstance(Interface.java:2)
> 	at javax.microedition.m3g.Graphics3D.<init>(Graphics3D.java:8)
> 	at javax.microedition.m3g.Graphics3D.getInstance(Graphics3D.java:2)
> 	at n.a(Unknown Source)
> 	at House.<init>(Unknown Source)
> 	... 6 more
> ```

it might be due to m3g , afaik this branch does not fully support m3g , try running on woess build, where mascotcapsule is at least implemented

**Comment by woesss** [comment]
The J2ME loader now supports Mascot Capsule.  
And Mascot Capsule and M3G have nothing in common.  
The implementation of M3G in the mod is identical.  
The logs say that the system cannot find it at all.  
Most likely because he installed a 64-bit build of the emulator, which is not suitable for a 32-bit OS.

**Comment by W1nKille3r** [comment]
> Same happens with City Bloxx. Btw my memory is SD Card+Internal. Maybe this is connected?
> 
> ```
> =================Error==================
> java.lang.RuntimeException: Init midlet failed
> 	at javax.microedition.shell.MidletThread.handleMessage(MidletThread.java:25)
> 	at android.os.Handler.dispatchMessage(Handler.java:107)
> 	at android.os.Looper.loop(Looper.java:207)
> 	at android.os.HandlerThread.run(HandlerThread.java:61)
> Caused by: java.lang.reflect.InvocationTargetException
> 	at java.lang.reflect.Constructor.newInstance(Native Method)
> 	at javax.microedition.shell.MicroLoader.loadMIDlet(MicroLoader.java:15)
> 	at javax.microedition.shell.MidletThread.handleMessage(MidletThread.java:23)
> 	... 3 more
> Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/ru.playsoftware.j2meloader-1/base.apk"],nativeLibraryDirectories=[/data/app/ru.playsoftware.j2meloader-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libjavam3g.so"
> 	at java.lang.Runtime.loadLibrary(Runtime.java:367)
> 	at java.lang.System.loadLibrary(System.java:1076)
> 	at javax.microedition.m3g.Platform.uiThreadAvailable(Platform.java:2)
> 	at javax.microedition.m3g.Interface.initNativePeer(Interface.java:2)
> 	at javax.microedition.m3g.Interface.<init>(Interface.java:5)
> 	at javax.microedition.m3g.Interface.getInstance(Interface.java:2)
> 	at javax.microedition.m3g.Graphics3D.<init>(Graphics3D.java:8)
> 	at javax.microedition.m3g.Graphics3D.getInstance(Graphics3D.java:2)
> 	at n.a(Unknown Source)
> 	at House.<init>(Unknown Source)
> 	... 6 more
> ```

???
