### ISSUE TITLE
5ud0ku crashes in some menus

### ISSUE THREAD

**Issue by easyaspi314** [nikita36078/J2ME-Loader#178]
**Emulator version:**
1.2.7.8-play

**Game version:**
5ud0ku 1.8.9, source code dug up and reuploaded [here](https://github.com/easyaspi314/5ud0ku/tree/0fc4641ffb69a6cff7e0d8323cd4d0aa34f77b28) for everyone's convenience

**Game resolution:**
``(For example, 240x320 or 640x360)``
Doesn't matter. 
**Device:**
LG G3

**Android version:**
Android 7.1.2 (Resurrection Remix 5.8.5). I have Xposed, but literally nothing is installed to it, and I got this crash without it enabled.

**Description of the issue:**

Clicking on either the Game or Specials menu items in the Preferences screen reliably causes a crash.

<details><summary>Stack trace (click to expand)</summary>

```                          
java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v7.app.e // cut off?
javax.microedition.lcdui.Displayable.getParentActivity()' on a null object reference                                                  
      at javax.microedition.lcdui.Item.getItemView(Item.java:185)                           
      at javax.microedition.lcdui.Form.getScreenView(Form.java:152)                         
      at javax.microedition.lcdui.Screen.getDisplayableView(Screen.java:95)                 
      at javax.microedition.shell.MicroActivity$1.process(MicroActivity.java:201)           
      at javax.microedition.lcdui.event.Event.run(Event.java:42)                            
      at android.os.Handler.handleCallback(Handler.java:751)                                
      at android.os.Handler.dispatchMessage(Handler.java:95)                                
      at android.os.Looper.loop(Looper.java:154)                                            
      at android.app.ActivityThread.main(ActivityThread.java:6236)                          
      at java.lang.reflect.Method.invoke(Native Method)                                     
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
      at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
```

</details>

**Comment by nikita36078** [comment]
Fixed
![screenshot_1520011153](https://user-images.githubusercontent.com/3035571/36912195-0e034658-1e57-11e8-8b8d-a4fe3eeaebe5.png)
![screenshot_1520011172](https://user-images.githubusercontent.com/3035571/36912196-0e21ddac-1e57-11e8-867f-49fe4ef988c0.png)

**Comment by easyaspi314** [comment]
Nah, the Play Store update just made it worse. 

Now, when I try to open the Preferences menu (not the submenu), I get this:
![hi](https://user-images.githubusercontent.com/6258309/37006398-30fc08f6-20a6-11e8-879d-bbcc205b1cc1.png)
While nothing is logged when this happens, in the [sister game k4kur0](https://wintermute.de/wap/k4kur0man.html?), which I can't find source for right now, hitting Preferences in the main menu does nothing but log this to logcat, which appears to be related:
<details><summary>Stack trace</summary>

```
03-05 18:56:51.716 14736 14990 W System.err: java.lang.IllegalStateException: The current thread must have a looper!                                                  
03-05 18:56:51.717 14736 14990 W System.err:    at android.view.Choreographer$1.initialValue(Choreographer.java:103)                                                  
03-05 18:56:51.717 14736 14990 W System.err:    at android.view.Choreographer$1.initialValue(Choreographer.java:100)                                                  
03-05 18:56:51.717 14736 14990 W System.err:    at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:160)                                                        
03-05 18:56:51.717 14736 14990 W System.err:    at java.lang.ThreadLocal.get(ThreadLocal.java:150)                                                                    
03-05 18:56:51.717 14736 14990 W System.err:    at android.view.Choreographer.getInstance(Choreographer.java:233)                                                     
03-05 18:56:51.717 14736 14990 W System.err:    at com.android.internal.view.animation.FallbackLUTInterpolator.createLUT(FallbackLUTInterpolator.java:48)             
03-05 18:56:51.717 14736 14990 W System.err:    at com.android.internal.view.animation.FallbackLUTInterpolator.createNativeInterpolator(FallbackLUTInterpolator.java:71)                                                                                 
03-05 18:56:51.717 14736 14990 W System.err:    at android.view.RenderNodeAnimatorSetHelper.createNativeInterpolator(RenderNodeAnimatorSetHelper.java:43)             
03-05 18:56:51.719 14736 14990 W System.err:    at android.graphics.drawable.AnimatedVectorDrawable$VectorDrawableAnimatorRT.createNativeChildAnimator(AnimatedVectorDrawable.java:1519)
03-05 18:56:51.719 14736 14990 W System.err:    at android.graphics.drawable.AnimatedVectorDrawable$VectorDrawableAnimatorRT.createRTAnimatorForGroup(AnimatedVectorDrawable.java:1366)                                                                  
03-05 18:56:51.719 14736 14990 W System.err:    at android.graphics.drawable.AnimatedVectorDrawable$VectorDrawableAnimatorRT.createRTAnimator(AnimatedVectorDrawable.java:1306)                                                                          
03-05 18:56:51.719 14736 14990 W System.err:    at android.graphics.drawable.AnimatedVectorDrawable$VectorDrawableAnimatorRT.parseAnimatorSet(AnimatedVectorDrawable.java:1288)                                                                          
03-05 18:56:51.719 14736 14990 W System.err:    at android.graphics.drawable.AnimatedVectorDrawable$VectorDrawableAnimatorRT.parseAnimatorSet(AnimatedVectorDrawable.java:1286)                                                                          
03-05 18:56:51.719 14736 14990 W System.err:    at android.graphics.drawable.AnimatedVectorDrawable$VectorDrawableAnimatorRT.parseAnimatorSet(AnimatedVectorDrawable.java:1286)                                                                          
03-05 18:56:51.719 14736 14990 W System.err:    at android.graphics.drawable.AnimatedVectorDrawable$VectorDrawableAnimatorRT.init(AnimatedVectorDrawable.java:1255)   
03-05 18:56:51.719 14736 14990 W System.err:    at android.graphics.drawable.AnimatedVectorDrawable.ensureAnimatorSet(AnimatedVectorDrawable.java:919)                
03-05 18:56:51.719 14736 14990 W System.err:    at android.graphics.drawable.AnimatedVectorDrawable.start(AnimatedVectorDrawable.java:902)                            
03-05 18:56:51.719 14736 14990 W System.err:    at android.graphics.drawable.AnimatedStateListDrawable$AnimatedVectorDrawableTransition.start(AnimatedStateListDrawable.java:339)                                                                        
03-05 18:56:51.719 14736 14990 W System.err:    at android.graphics.drawable.AnimatedStateListDrawable.selectTransition(AnimatedStateListDrawable.java:226)           
03-05 18:56:51.719 14736 14990 W System.err:    at android.graphics.drawable.AnimatedStateListDrawable.onStateChange(AnimatedStateListDrawable.java:146)              
03-05 18:56:51.719 14736 14990 W System.err:    at android.graphics.drawable.Drawable.setState(Drawable.java:735)                                                     
03-05 18:56:51.719 14736 14990 W System.err:    at android.widget.CompoundButton.drawableStateChanged(CompoundButton.java:462)                                        
03-05 18:56:51.719 14736 14990 W System.err:    at android.view.View.refreshDrawableState(View.java:18069)                                                            
03-05 18:56:51.719 14736 14990 W System.err:    at android.widget.CompoundButton.setChecked(CompoundButton.java:145)                                                  
03-05 18:56:51.719 14736 14990 W System.err:    at javax.microedition.lcdui.ChoiceGroup.setSelectedIndex(ChoiceGroup.java:362)                                        
03-05 18:56:51.719 14736 14990 W System.err:    at c.e(Unknown Source)             
03-05 18:56:51.719 14736 14990 W System.err:    at c.<init>(Unknown Source)        
03-05 18:56:51.719 14736 14990 W System.err:    at de.wintermute.kakuro.midlet.KakuroMidlet.h(Unknown Source)                                                         
03-05 18:56:51.720 14736 14990 W System.err:    at ae.commandAction(Unknown Source)
03-05 18:56:51.720 14736 14990 W System.err:    at javax.microedition.lcdui.event.CommandActionEvent.process(CommandActionEvent.java:68)                             
03-05 18:56:51.720 14736 14990 W System.err:    at javax.microedition.lcdui.event.EventQueue.run(EventQueue.java:259)                                                 
03-05 18:56:51.720 14736 14990 W System.err:    at java.lang.Thread.run(Thread.java:761)
```

**Comment by nikita36078** [comment]
Weird, I can't catch such bug in both games (Android 8.1), will try later on other Android versions.

**Comment by nikita36078** [comment]
Fixed.
