### ISSUE TITLE
Ошибка на Android 11: no read access for the input zip file

### ISSUE THREAD

**Issue by Helltar** [nikita36078/J2ME-Loader#905]
**Emulator version:**

1.7.5

**Description of the issue:**

Я передаю файл .jar из своей программы способом типа:

``` java
Intent intent = new Intent(Intent.ACTION_VIEW);
intent.setDataAndType(Uri.fromFile(file), "application/java-archive");
startActivity(intent);
```

Сам файл находится в **Documents/...**

Получаю ошибку **_Error: no read access for the input zip file_**:

```
05-28 14:19:10.046 12727 12727 W System.err: s5.a: no read access for the input zip file
05-28 14:19:10.047 12727 12727 W System.err: 	at o5.a.d(ZipFile.java:18)
05-28 14:19:10.047 12727 12727 W System.err: 	at o5.a.a(ZipFile.java:2)
05-28 14:19:10.047 12727 12727 W System.err: 	at d7.a.d(AppInstaller.java:2)
05-28 14:19:10.047 12727 12727 W System.err: 	at d7.b.d(Unknown Source:87)
05-28 14:19:10.047 12727 12727 W System.err: 	at r4.a.d(SingleCreate.java:3)
05-28 14:19:10.047 12727 12727 W System.err: 	at d4.o.c(Single.java:1)
05-28 14:19:10.047 12727 12727 W System.err: 	at r4.d$a.run(SingleSubscribeOn.java:1)
05-28 14:19:10.047 12727 12727 W System.err: 	at t4.h.call(ScheduledDirectTask.java:2)
05-28 14:19:10.047 12727 12727 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-28 14:19:10.047 12727 12727 W System.err: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
05-28 14:19:10.047 12727 12727 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-28 14:19:10.047 12727 12727 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-28 14:19:10.048 12727 12727 W System.err: 	at java.lang.Thread.run(Thread.java:923)
```

Android 11.

Версия 1.7.4 работает без проблем.

**Comment by woesss** [comment]
На Android 11 оно в принципе работать не должно - uri со схемой `file` запретили передавать между приложениями ещё где-то в районе Андроид  8. Используйте `FileProvider` для шаринга. Эмулятор перешёл на scoped storage и на Андроид 11+ больше не имеет прямого доступа в ФС.

**Comment by Helltar** [comment]
Ок, посмотрю, тем не менее преждняя версия 1.7.4 все принимает отлично на Android 11. Ну и доступ к публичным каталогам documents, downloads... все еще можно получать напрямую, даже без разрешений в манифесте.
